spring:
  datasource:
   password: 1234
   username: postgres
   url: jdbc:postgresql://localhost:5432/clientes
  rabbitmq:
       host: localhost
       port: 5672
       username: diego
       password: 1234
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  
